#!/usr/bin/env bash
[ ${BASH_VERSION%%.*} -lt 4 ] && { echo "Requires bash 4+"; exit 1; }

set \
  -o errexit \
  -o pipefail

showHelp() {
  printf "\nusage: ./pj "
  printf "<action:build|publish|deploy|start|stop|destroy|clean|list> "
  printf "<region:[root]>"
  printf "<config:[config.json]>"
  printf "\n\n"
}
[[ $# -eq 0 ]] && { showHelp; exit 1; }

# Defaults
################################################################################
Region="root"
Config="./config.json"

# Parameters
################################################################################
Action="$1"

# Optional Options
################################################################################
declare -A Options
Options[build]="Container"
Options[publish]=""
Options[deploy]=""
Options[start]=""
Options[stop]=""
Options[destroy]=""
Options[clean]=""
Options[list]=""

# Dependencies
################################################################################
Depends=("aws" "jq" "docker" "docker-compose")
for d in ${Depends[@]}; do
  [[ $(which $d) ]] || { echo "Missing dependency: $d"; ! break; }
done || exit

# Helpers
################################################################################
parseOptions() {
  declare \
    options opt arg

  [[ -n ${Options[$Action]} ]] && {
    options=(${Options[$Action]//,/ })
    for opt in ${options[@]}; do declare -g $opt=""; done
  }

  while [ $# -gt 0 ]; do
    arg=""

    case $1 in
      --region=*) arg=Region;;
      --config=*) arg=Config;;
    esac

    [[ -z $arg ]] && {
      case $Action in
        build)
          case $1 in
            -c=*|--container=*) arg=Container;;
          esac
          ;;
      esac
    }

    [[ -z $arg ]] && { printf "\nInvalid argument:[$1]\n\n"; exit 1; }

    declare -g "$arg=${1#*=}"
    shift
  done
  return
}

project() {
  local \
    file="$Config"

  [[ -r $file ]] || { echo "Missing project config file:[$file]"; return 1; }
  [[ $1 = "echo" ]] && { cat "$file" | jq -e '.'; return; }

  declare args=("$@") result rC
  [[ ${#args[@]} -gt 1 ]] && {
    result=$(cat "$file"|jq -rce ${args[@]:0:${#args[@]} - 1} ".${args[-1]}") \
      || return
  } \
  || result=$(cat "$file" | jq -rce ".${@}")

  rC=$?
  [[ ! $result =~ null|'{}'|'[]' ]] && echo $result

  return $rC
}

tagFile() {
  declare t=$(cat "$1")
  echo "${t//$2/$3}" > "$1"
}

makeTemplate() {
  declare \
    file=$1 \
    template=$2 \
    version

  cp $file $template

  tagFile $template "{{Version}}" "$Version"
  #tagFile $template "{{VersionZip}}" "${Version//./}"
  tagFile $template "{{Project}}" "${Name}"
  tagFile $template "{{Namespace}}" "$Namespace"

  return
}

# Bucket Management (S3)
################################################################################
createBucket() {
  local \
    region="$1" \
    bucket="$2"

  declare \
    prefix="${Namespace,,}-${Name,,}" \
    constraint="$region" 

  bucket="$prefix-$bucket"

  [[ $region == "root" ]] \
    && constraint="${Regions[root]}" \
    || bucket+="-$region" 

  printf -- "- Creating bucket:[$bucket] ... "

  fetchBucket "$bucket" &> /dev/null && {
    printf "exists\n"
    return
  }

  [[ $region != "us-east-1" ]] \
  && constraint="--create-bucket-configuration LocationConstraint=$constraint" \
  || constraint=""

  declare result
  result=$($Aws s3api create-bucket $constraint \
    --bucket "$bucket" \
    --acl private) \
  || { printf "error!\n\n$result\n"; return 1; }

  printf "done!\n"
  return
}

publishBucket() {
  local \
    region="$1" \
    bucket="$2"

  declare \
    prefix="${Namespace,,}-${Name,,}" \
    src dst

  [[ $region == "root" ]] && {

    declare \
      templates=() \
      bundles=() \
      packages=() \
      excludes=(".DS_Store") \
      file template tags tag folder bundle package url

    project --arg b "$bucket" 'publish.buckets[$b]' &> /dev/null \
    && \
    project --arg b "$bucket" 'publish.buckets[$b]["templates"]' &> /dev/null \
    && {
      printf -- "- Creating templates for bucket:[$bucket]\n"

      tags=$(project --arg b "$bucket" 'publish.buckets[$b]["templates"]')
      [[ $tags != 'true' ]] \
        && tags=($(project --arg b "$bucket" \
          'publish.buckets[$b]["templates"][]')) \
        || unset tags

      for file in $(find ./buckets/$bucket/ -type f); do
        template=${file##*/} \
          && template="${file%/*}/${template%.*}.template"
        makeTemplate "$file" "$template"

        [[ ${#tags[@]} -gt 0 ]] \
          && for tag in ${tags[@]}; do
            tagFile "$template" "{{${tag%%=*}}}" "$(project ${tag#*=})"
          done

        templates+=("$template")
        excludes+=("$file")
      done
    }

    project --arg b "$bucket" 'publish.buckets[$b]' &> /dev/null \
    && \
    project --arg b "$bucket" 'publish.buckets[$b]["bundles"]' &> /dev/null \
    && \
    for folder in ./buckets/$bucket/*/; do

      project \
        --arg b "$bucket" \
        --arg f "$(basename $folder)" \
        'publish.buckets[$b].bundles|index($f)' \
        1> /dev/null \
      || continue

      bundle="$(basename $folder).tgz"

      printf -- "- Bundling folder:[$folder] as bundle:[$bundle]\n"
      (cd "${folder}../" && tar -czf "$bundle" "${bundle%.*}/")
      bundles+=("$(dirname $folder)/$bundle")

      exclude="${folder#*/}" && exclude=${exclude%/*}
      excludes+=(${folder#*/}*)
    done

    project --arg b "$bucket" 'publish.buckets[$b]' &> /dev/null \
    && \
    project --arg b "$bucket" 'publish.buckets[$b]["packages"]' &> /dev/null \
    && {
      packages=($(project \
        --arg b "$bucket" \
        'publish.buckets[$b].packages|keys[]'))
      [[ ${#packages} -gt 0 ]] && {
        folder="./buckets/$bucket/packages"
        mkdir -p "$folder"
        for package in ${packages[@]}; do
          printf -- "- Downloading package:[$package] to folder:[$folder]\n"
          url=$(project \
            --arg b "$bucket" \
            --arg p "$package" \
            'publish.buckets[$b].packages[$p]')
          curl -L -o $folder/$package $url
        done
      }
    }

    src="./buckets/$bucket/"
    dst="$prefix-$bucket"

    project --arg b "$bucket" 'publish.buckets[$b]' &> /dev/null \
    && \
    project --arg b "$bucket" 'publish.buckets[$b]["version"]' &> /dev/null \
    && {
      declare version
      version=$(project --arg b "$bucket" 'publish.buckets[$b]["version"]')
      case $version in
        'true') dst+="/$Version";;
        'false') dst+='';;
        *)
          [[ $version != 'false' && ! $version =~ ^[0-9.]+$ ]] \
            && version=$(project $version)

          dst+="/$version"
          ;;
      esac
    }

    printf -- "- Publishing folder:[$src] to bucket:[$dst]\n"
    $Aws s3 sync "$src" "s3://$dst" --delete ${excludes[@]/#/--exclude }
    printf "\n"

    [[ ${#bundles} -ne 0 ]] \
      && {
        for bundle in ${bundles[@]}; do rm $bundle; done
      }

    [[ ${#packages} -gt 0 ]] \
      && {
        rm -Rf "./buckets/$bucket/packages"
      }

    [[ ${#templates} -gt 0 ]] \
      && {
        for template in ${templates[@]}; do rm $template; done
      }

    return 0
  }

  src="$prefix-$bucket"
  dst="$prefix-$bucket-$region"

  printf -- "- Sync bucket:[$dst] from region:[${Regions[root]}]\n"
  $Aws s3 sync "s3://$src" "s3://$dst" \
    --source-region ${Regions[root]} \
    --delete \
    --exclude ".DS_Store"
  printf "\n"

  return
}

fetchBucket() {
  local \
    bucket="$1"

  declare result
  result=$($Aws s3api head-bucket --bucket "$bucket") || return

  echo -n "$result"

  return
}

destroyBucket() {
  local \
    region="$1" \
    bucket="$2"

  declare \
    prefix="${Namespace,,}-${Name,,}" \
    constraint="$region" 

  bucket="$prefix-$bucket"

  [[ $region == "root" ]] || bucket+="-$region" 

  printf -- "- Destroying bucket:[$bucket] ... "

  fetchBucket "$bucket" &> /dev/null || { printf "missing\n"; return; }

  declare result
  result=$($Aws s3 rm "s3://$bucket" --recursive) \
  || { printf "error!\n\n$result\n"; return 1; }

  result=$($Aws s3api delete-bucket --bucket "$bucket") \
  || { printf "error!\n\n$result\n"; return 1; }

  printf "done!\n"
  return
}

publishBuckets() {

  [[ -d $PWD/buckets && $(project publish.buckets) != "false" ]] || {
    printf -- "- Skipping buckets\n"
    return
  }

  declare folder bucket
  for folder in $PWD/buckets/*/; do
    bucket="$(basename $folder)"

    [[ $(project \
      --arg b "$bucket" \
      ' as {publish:{buckets:{($b):$p}}}?//$x | $p == false') \
    ]] \
      && { printf -- "- Skipping bucket:[$bucket] ...\n"; continue; }

    [[ ${Regions[run]} == ${Regions[root]} ]] && {
      createBucket "root" "$bucket" \
        && publishBucket "root" "$bucket" \
        || ! break
    }

    createBucket "${Regions[run]}" "$bucket" \
      && publishBucket "${Regions[run]}" "$bucket" \
      || ! break
  done

  return
}

destroyBuckets() {

  [[ -d $PWD/buckets && $(project destroy.buckets) != "false" ]] || {
    printf -- "- Skipping buckets\n"
    return
  }

  declare folder bucket
  for folder in $PWD/buckets/*/; do
    bucket="$(basename $folder)"

    [[ $(project \
      --arg b "$bucket" \
      ' as {destroy:{buckets:{($b):$p}}}?//$x | $p == false') \
    ]] \
      && { printf -- "- Skipping bucket:[$bucket] ...\n"; continue; }

    [[ ${Regions[run]} == ${Regions[root]} ]] && {
      destroyBucket "root" "$bucket" || ! break
    }

    destroyBucket "${Regions[run]}" "$bucket" || ! break
  done

  return
}

# Container Management
################################################################################
buildContainer() {
  declare \
    container="$1" \
    image="$2" \
    folder="$3"

  declare -A archs

  project --arg c "$container" 'publish.containers[$c]' &> /dev/null \
  && \
  project --arg c "$container" \
    'publish.containers[$c]["architectures"]' &> /dev/null \
  && {
    declare arch
    for arch in $(project --arg c "$container" \
      'publish.containers[$c].architectures[]'); \
    do
      archs[$arch]=$(project --arg a $arch \
        'publish.containers.architectures[$a]')
    done
  }

  [[ ${#archs[@]} -eq 0 ]] && {
    project 'publish.containers["architectures"]' &> /dev/null \
    && {
      for arch in $(project 'publish.containers.architectures|keys[]'); do
        archs[$arch]=$(project --arg a $arch \
          'publish.containers.architectures[$a]')
      done
    } \
    || archs[x86_64]="local"
  }

  declare arch host tags args builder
  for arch in ${!archs[@]}; do
    printf -- "- Building container image:[$image] for arch:[$arch]"

    host="${archs[$arch]}"
    unset DOCKER_HOST
    [[ $host != "local" ]] && {
      printf " on host:[$host]"
      export DOCKER_HOST="ssh://$host"
    }

    builder="$Docker build $DockerBuildFlags"

    tags=("$image")
    [[ ${#archs[@]} -gt 1 ]] && tags+=("$image-$arch")

    args=("ARCH=$arch")

    builder+=" ${tags[@]/#/-t } ${args[@]/#/--build-arg } $folder"
    [[ -z $Container ]] && {
      printf "..."
      $builder &> /dev/null \
      || {
        printf "error!\n\nTry building directly with:\n$builder\n\n"
        ! break
      }
      printf "done!\n"
    } || {
      printf "\n"
      $builder \
      || {
        printf "error!\n\nTry building directly with:\n$builder\n\n"
        ! break
      }
    }
  done

  unset DOCKER_HOST

  return
}

buildContainers() {
  declare \
    folder container image builder

  [[ -d $PWD/containers ]] || return 0

  [[ -z $Container ]] && {
    for folder in $PWD/containers/*/; do
      container="$(basename $folder)"
      image="$Namespace/$container:$Version"
      buildContainer "$container" "$image" "$folder"
    done
  }

  [[ -n $Container ]] && {
    folder="$PWD/containers/$Container"
    [[ ! -d $PWD/containers/$Container ]] && {
      printf "error!\n\nMissing folder:[$folder] for container:[$Container]\n\n"
      return 1
    }

    image="$Namespace/$Container:$Version"
    buildContainer "$Container" "$image" "$folder"
  }

  return 0
}

createContainerRepo() {
  local \
    image="$1"

  printf -- "- Creating repository for container:[$image] ... "
  declare result
  result=$($Aws ecr create-repository \
    --repository-name "$image" \
    --image-scanning-configuration "scanOnPush=true" \
    --encryption-configuration "encryptionType=KMS") \
  || { printf "error!\n\n$result\n"; return 1; }

  printf "done!\n"
  return
}

deleteContainerRepo() {
  local \
    image="$1"

  printf -- "- Deleting repository for container:[$image] ... "
  declare result
  result=$($Aws ecr delete-repository --force --repository-name "$image") \
  || { printf "error!\n\n$result\n"; return 1; }

  printf "done!\n"
  return
}

publishContainer() {
  declare \
    container="$1" \
    image="$2" \
    repo="$3"

  declare -A archs

  project --arg c "$container" 'publish.containers[$c]' &> /dev/null \
  && \
  project --arg c "$container" \
    'publish.containers[$c]["architectures"]' &> /dev/null \
  && {
    declare arch
    for arch in $(project --arg c "$container" \
      'publish.containers[$c].architectures[]'); \
    do
      archs[$arch]=$(project --arg a $arch \
        'publish.containers.architectures[$a]')
    done
  }

  [[ ${#archs[@]} -eq 0 ]] && {
    project 'publish.containers["architectures"]' &> /dev/null \
    && {
      for arch in $(project 'publish.containers.architectures|keys[]'); do
        archs[$arch]=$(project --arg a $arch \
          'publish.containers.architectures[$a]')
      done
    } \
    || archs[x86_64]="local"
  }

  declare arch host tag manifest=()
  for arch in ${!archs[@]}; do
    printf -- "- Publishing container image:[$image] with arch:[$arch]"

    host="${archs[$arch]}"
    unset DOCKER_HOST
    [[ $host != "local" ]] && {
      printf " from host:[$host]"
      export DOCKER_HOST="ssh://$host"
    }

    tag="$image"
    [[ ${#archs[@]} -gt 1 ]] && {
      tag+="-$arch"
      manifest+=("$repo/$tag")
    }

    printf "\n"

    $Docker tag $tag $repo/$tag \
      && $Docker push $repo/$tag
    rC=$?

    $Docker image rm $repo/$tag &> /dev/null
    [[ $rC -eq 0 ]] || ! break

    printf "\n"
  done

  unset DOCKER_HOST

  [[ ${#archs[@]} -gt 1 ]] && {
    docker manifest create "$repo/$image" ${manifest[@]/#/--amend }
    for arch in ${!archs[@]}; do
      [[ $arch == "x86_64" ]] && continue
      docker manifest annotate --arch $arch "$repo/$image" "$repo/$image-$arch"
    done
    docker manifest push "$repo/$image"
    docker manifest rm "$repo/$image"
  }

  printf "done!\n"
  return
}

publishContainers() {
  local \
    region="${Regions[run]}"

  declare \
    account repo
  
  [[ -d $PWD/containers && $(project publish.containers) != "false" ]] || {
    printf -- "- Skipping containers ...\n"
    return
  }

  account="$($Aws sts get-caller-identity --output text --query 'Account')" \
    && repo="$account.dkr.ecr.$region.amazonaws.com" \
    || return

  declare login
  login=$($Aws ecr get-login-password --region $region \
    | $Docker login --username AWS --password-stdin $repo 2>&1) \
    || { printf "error!\n\n$login\n"; return 1; }

  declare folder container image
  for folder in $PWD/containers/*/; do
    container="$(basename $folder)"
    image="$Namespace/$container:$Version"

    project --arg c "$container" 'publish.containers[$c]' &> /dev/null \
    && \
    project --arg c "$container" 'publish.containers[$c]==false' &> /dev/null \
    && {
      printf -- "- Skipping container:[$container] ...\n"
      continue
    }

    $Aws ecr describe-repositories \
      --repository-names "$Namespace/$container" &> /dev/null \
    || {
      createContainerRepo "$Namespace/$container" \
        || ! break
    }

    publishContainer "$container" "$image" "$repo"
  done

  return
}

destroyContainers() {
  declare \
    folder container image cleaner

  [[ -d $PWD/containers && $(project publish.containers) != "false" ]] || {
    printf -- "- Skipping containers ...\n"
    return
  }

  for folder in $PWD/containers/*/; do
    container="$(basename $folder)"
    image="$Namespace/$container"

    [[ $(project \
      --arg c "$container" \
      ' as {destroy:{containers:{($c):$p}}}?//$x | $p == false') \
    ]] \
      && { printf -- "- Skipping container:[$container] ...\n"; continue; }

    $Aws ecr describe-repositories --repository-names $image &> /dev/null && {
      deleteContainerRepo "$image" || ! break
    }

    printf "done!\n"
  done

  return
}

cleanContainers() {
  declare \
    folder image cleaner

  [[ -d $PWD/containers ]] || return 0

  for folder in $PWD/containers/*/; do
    image="$Namespace/$(basename $folder)"
    cleaner="$Docker rmi -f $($Docker images -a -q "$image")"

    printf -- "- Removing container images:[$image:*] ... "
    $cleaner &> /dev/null || {
      printf "error!\n\nTry removing directly with:\n$cleaner\n\n"
      ! break
    }
    printf "done!\n"
  done

  return
}

# Secret Management (SSM Parameters)
################################################################################
publishSecret() {
  local \
    key="$1"

  declare path="/$Namespace/$Name/$key"

  declare secret
  secret="$(project --arg k "$key" 'secrets[$k]//"init"')"

  declare result
  result=$($Aws ssm put-parameter --name "$path" --value "$secret" \
    --type "String" \
    --no-overwrite) \
  || { printf "error!\n\n$result\n"; return 1; }

  return
}

fetchSecret() {
  local \
    key="$1"

  declare path="/$Namespace/$Name/$key"

  declare result
  result=$($Aws ssm get-parameter --name "$path" \
    --output text \
    --query 'Parameter.Value' \
  2> /dev/null)
  case $? in
    254|255) # ParameterNotFound
      printf "fail!\n"
      printf "\nERROR: No Key found!\n\n"
      return 1
      ;;

    0) # ParameterFound
      echo -n "$result"
      ;;

    *) # AWS Config Issue or other gremlins ...
      printf "error!\n"
      printf "\nERROR: Check your AWS CLI config, something isn't right.\n"
      return 1
      ;;
  esac

  return
}

deleteSecret() {
  local \
    key="$1"

  declare path="/$Namespace/$Name/$key"

  declare result
  result=$($Aws ssm delete-parameter --name "$path") || {
    printf "error!\n\n$result\n"
    return 1
  }

  return
}

publishSecrets() {
  declare \
    secrets

  [[ $(project publish.secrets) != "false" ]] || {
    printf -- "- Skipping secrets\n"
    return
  }

  secrets=($(project 'secrets|keys|.[]'))

  declare secret result
  for secret in ${secrets[@]}; do
    printf -- "- Publishing secret:[$secret] ... "

    fetchSecret "$secret" &> /dev/null && {
      printf -- "exists\n"
      continue
    }

    result=$(publishSecret "$secret") || {
      printf "$result"
      ! break
    }

    printf "done\n"
  done

  return
}

destroySecrets() {
  declare \
    secrets

  [[ $(project destroy.secrets) != "false" ]] || {
    printf -- "- Skipping secrets\n"
    return
  }

  secrets=($(project 'secrets|keys|.[]'))

  declare secret result
  for secret in ${secrets[@]}; do
    printf -- "- Deleting secret:[$secret] ... "

    fetchSecret "$secret" &> /dev/null || {
      printf -- "missing\n"
      continue
    }

    result=$(deleteSecret "$secret") || {
      printf "$result"
      ! break
    }

    printf "done\n"
  done

  return
}

# Stack Management (CloudFormation)
################################################################################
buildStack () {
  printf "Building [$Namespace/$Name]\n"

  buildContainers

  printf -- "- Build Complete! (v$Version)\n\n"

  return
}

publishStack () {
  printf "Publishing [$Namespace/$Name] to [$Account/${Regions[run]}]\n"

  publishBuckets
  publishContainers
  publishSecrets
  # publishMacros

  printf -- "- Publish Complete! (v$Version)\n\n"

  return
}

makeParameters() {
  declare \
    parameters=(
      "Version=$Version"
      "Name=$Name"
      "Namespace=$Namespace"
      "RegionsRoot=${Regions[root]}"
    )

  [[ -v Domain ]] && parameters+=("Domain=$Domain")

  $(project --arg r "${Regions[run]}" 'regions[$r]|keys|length > 0') && {
    parameters+=($(project \
      --arg region "${Regions[run]}" \
      'regions[$region]
      | to_entries
      | map(
          (
            if .value|type|inside("array|object") then
              .value|tojson
            else
              .value
            end
          ) as $param
          |
          "Region\(.key/""|first|=ascii_upcase|add)=\($param)"
        )
      | .[]'))
  }

  project parameters &> /dev/null \
    && {
    parameters+=($(project 'parameters
      | to_entries
      | map(
          (
            if .value|type|inside("array|object") then
              .value|tojson
            else
              .value
            end
          ) as $param
          |
          "\(.key)=\($param)"
        )
      | .[]'))
  }

  project secrets &> /dev/null \
    && {
    parameters+=($(project \
      --arg n "$Namespace" \
      --arg p "$Name" \
      'secrets
      | to_entries
      | map("\(.key)=/\($n)/\($p)/\(.key)")
      | .[]'))
  }

  echo "${parameters[@]}"
  return
}

deployStack () {
  printf "Deploying [$Namespace/$Name] in [$Account/${Regions[run]}]\n"

  declare \
    stack="$Namespace-$Name" \
    parameters=("State=On")

  parameters+=($(makeParameters)) || return

  makeTemplate "$PWD/stack.yml" "$PWD/stack.template"

  declare bucket=""
  [[ -d $PWD/buckets && $(project publish.buckets) != "false" ]] && {

    [[ -d $PWD/buckets/templates ]] \
      && bucket="${Namespace,,}-${Name,,}-templates-${Regions[run]}" \
      || {
        declare buckets=( $(ls buckets/) )
        bucket="${Namespace,,}-${Name,,}-${buckets[0]}-${Regions[run]}"
      }

    bucket="--s3-bucket $bucket --s3-prefix $Version"
  }

  printf -- "- Deploying CloudFormation stack:[$stack] ...\n"
  declare rC
  $Aws cloudformation deploy $bucket \
    --stack-name "$stack" \
    --template-file stack.template \
    --capabilities CAPABILITY_IAM CAPABILITY_AUTO_EXPAND \
    --parameter-overrides ${parameters[@]} \
  && rC=$? || rC=$?

  rm "$PWD/stack.template"

  [[ $rC -ne 0 ]] && {
    printf "\nerror!\n\nCaught exit with code:[$rC]\n"
    return 1
  }
  printf -- "- Deployment Complete! (v$Version)\n\n"

  return
}

updateStack () {
  declare \
    state

  [[ $Action = "start" ]] && {
    printf "Starting "
    state="On"
  } || {
    printf "Stopping "
    state="Off"
  }

  printf "[$Namespace/$Name] in [$Account/${Regions[run]}]\n"

  declare \
    stack="$Namespace-$Name" \
    parameters=(
      "State=$state"
    )

  parameters+=($(makeParameters)) || return

  makeTemplate "$PWD/stack.yml" "$PWD/stack.template"

  declare bucket=""
  [[ -d $PWD/buckets && $(project publish.buckets) != "false" ]] && {

    [[ -d $PWD/buckets/templates ]] \
      && bucket="$Namespace-$Name-templates-${Regions[run]}" \
      || {
        declare buckets=( $(ls buckets/) )
        bucket="$Namespace-$Name-${buckets[0]}-${Regions[run]}"
      }

    bucket="--s3-bucket $bucket --s3-prefix $Version"
  }

  printf -- "- Updating CloudFormation stack:[$stack] ...\n"
  declare rC
  $Aws cloudformation deploy $bucket \
    --stack-name "$stack" \
    --template-file stack.template \
    --capabilities CAPABILITY_IAM CAPABILITY_AUTO_EXPAND \
    --parameter-overrides ${parameters[@]} \
  && rC=$? || rC=$?

  rm "$PWD/stack.template"

  [[ $rC -ne 0 ]] && {
    printf "\nerror!\n\nCaught exit with code:[$rC]\n"
    return 1
  }
  printf -- "- Update Complete! (v$Version)\n\n"

  return
}

destroyStack () {
  printf "Destroying [$Namespace/$Name] in [$Account/${Regions[run]}]\n"

  declare \
    stack="$Namespace-$Name" \

  printf -- "- Asking CloudFormation to delete stack:[$stack] ... "
  $Aws cloudformation delete-stack --stack-name "$stack" \
    || return
  printf "done!\n"

  printf -- "- Waiting for CloudFormation to finish ... "
  $Aws cloudformation wait stack-delete-complete --stack-name "$stack" \
    || return
  printf "done!\n"

  destroySecrets
  destroyContainers
  destroyBuckets

  printf -- "- Completely Destroyed! (v$Version)\n\n"

  return
}

cleanStack () {
  printf "Cleaning [$Namespace/$Name]\n"

  cleanContainers

  printf -- "- Completely Clean! (v$Version)\n\n"

  return
}

# Init
################################################################################
parseOptions "${@:2}" \
  && Version="$(project version)" \
  && Name="$(project name)" \
  && Namespace="$(project namespace)" \
  && {
    Domain="$(project domain)" || unset Domain
  } \
  && Account="$(project account)" \
  || { echo "Invalid config:[$Config]"; exit 1; }

declare -A Regions \
  && Regions[root]="$(project regions.root)" \
  && Regions[all]=$(project 'regions|keys|map(select(.!="root"))|.[]') \
  || {
    echo "Missing or invalid property:[regions] in config:[$Config]"
    exit 1
  }

[[ $Region =~ root|${Regions[root]} ]] && Regions[run]="${Regions[root]}" \
|| {
  case $Region in
    'all')
      printf "\nStarting synchronous execution for ALL regions\n\n"
      $0 $Action --region=root --config="$Config" && {
        for region in ${Regions[all]}; do
          [[ $region = ${Regions[root]} ]] && continue
          $0 $Action --region=$region --config=$Config || ! break
        done
      }
      exit
      ;;

    *)
      [[ ${Regions[all]} =~ "$Region" ]] && Regions[run]="$Region" \
      || {
        echo "Specified region:[$Region] is not in config:[$Config]"
        exit 1
      }
  esac
}

export DOCKER_BUILDKIT=1
Docker="$(which docker)"
DockerBuildFlags="--force-rm --compress"

export AWS_PROFILE="${Account:-"default"}"
Aws="$(which aws) --region ${Regions[run]}"

# Controller
################################################################################
case $Action in

  'fetchSecret') fetchSecret 'SwarmToken';;

  'build') buildStack;;
  'publish') publishStack;;
  'deploy') deployStack;;
  'start'|'stop') updateStack;;
  'destroy') destroyStack;;
  'clean') cleanStack;;

  'list')
    echo "Listing deployments in region:[${Regions[run]}]"
    fields="Id:StackId,Name:StackName,Status:StackStatus"
    $Aws cloudformation describe-stacks \
      --query "Stacks[?starts_with(StackName,'$Namespace')].{$fields}"
    ;;

  'wipe'|'reset') printf "\nComing soon... nuke it all...\n";;

  *) showHelp; exit 1;;

esac

exit